name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: nezmuzgcp
  REGION: asia-southeast1
  SERVICE_NAME: saas-be
  IMAGE_NAME: asia-southeast1-docker.pkg.dev/nezmuzgcp/saas-repo/saas-be

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Required permissions for Workload Identity Federation
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SA_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate Docker
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Container
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          env_vars: |
            NODE_ENV=production
          # Pulls DATABASE_URL from GCP Secret Manager and assigns it to Cloud Run environment
          secrets: |
            DATABASE_URL=DATABASE_URL:latest
